data = {}
seed = rand( 1000 ).to_s()
data[ 'email' ] = 'Test'+seed+'@null.com'
data[ 'phone_area' ] = '45' + rand( 10 ).to_s()
data[ 'phone_prefix' ] = '54' + rand( 10 ).to_s()
data[ 'phone_suffix' ] = '654' + rand( 10 ).to_s()
data[ 'phone' ] = data[ 'phone_area'] + data[ 'phone_prefix'] + data[ 'phone_suffix']
data[ 'name' ]		= "Test"+seed
data[ 'address' ] = seed+' S Bristol St'
data[ 'city' ] = 'Santa Ana'
data[ 'state' ] = 'California'
data[ 'zip' ] = '92704'
#data[ 'name' ]		= business.business_name
#data[ 'phone' ]		= business.local_phone
#data[ 'address' ]	= business.address + ' ' + business.address2
#data[ 'zip' ]		= business.zip
data[ 'first_name' ]	= business.contact_first_name
data[ 'last_name' ] 	= business.contact_last_name
#data[ 'email' ] 	= 'netversatest75@gmail.com'#business.yahoos.first.email
data[ 'password' ]	= 'applesunday'#business.yahoos.first.password
data[ 'website' ]	= business.company_website
data[ 'short_description' ] = business.business_description
data[ 'hours' ]		= Getfav.consolidate_hours( business )
data[ 'payment_methods' ] = "All"
data[ 'monOpen' ]	= business.monday_open
data[ 'monClose' ]	= business.monday_close
data[ 'tuesOpen' ]	= business.tuesday_open
data[ 'tuesClose' ]	= business.tuesday_close
data[ 'wedOpen' ]	= business.wednesday_open
data[ 'wedClose' ]	= business.wednesday_close
data[ 'thurOpen' ]	= business.thursday_open
data[ 'thurClose' ]	= business.thursday_close
data[ 'fridOpen' ]	= business.friday_open
data[ 'fridClose' ]	= business.friday_close
data[ 'satOpen' ]	= business.saturday_open
data[ 'satClose' ]	= business.saturday_close
data[ 'sunOpen' ]	= business.sunday_open
data[ 'sunClose' ]	= business.sunday_close
data

