source 'https://rubygems.org'

gem 'rails', '3.2.2'
gem 'mysql2'
group :assets do
  gem "zurb-foundation"
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'eventmachine', '1.0.0.beta4'
  gem 'uglifier', '>= 1.0.3'
end
gem 'jquery-rails'
gem 'devise'
gem 'haml'
gem 'haml-rails'
gem 'capistrano'
gem 'rvm-capistrano'
gem 'zip'
gem 'activeadmin'
gem "meta_search",    '>= 1.1.0.pre'
gem 'acts_as_tree'
gem 'acts_as_list'
gem 'rabl'
gem 'mail'
gem 'delayed_job_active_record'
gem 'formtastic'
gem 'cerebus'
