development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: contact_development
  pool: 5
  username: root
  password:
  host: localhost

test: &test
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: contact_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: contact
  pool: 5
  username: contact
  password: "2LCuNQ2nAq"
  host: localhost

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: contact
  pool: 5
  username: contact
  password: "2LCuNQ2nAq"
  host: localhost

cucumber:
  <<: *test
