# IMPORTANT: This file is generated by backburner-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of backburner-rails. Consider adding your own code to a new file
# instead of editing this one. backburner will automatically load all features/**/*.rb
# files.


begin
  require 'backburner'
  require File.join(File.dirname(__FILE__),'../config/application')
  puts "Backburner.work('business-manage')"
  ENV['RAILS_ENV'] = 'production'
  Contact::Application.initialize!
  Backburner.work('business-manage')
  
  rescue
    puts 'backburner rake task not available (backburner not installed)'
  end

