defaults: &defaults
  adapter: mysql2
  host: localhost
  username: root
  password: 

development:
  <<: *defaults
  database: contact_development
  
test:
  <<: *defaults
  database: contact_test

production:
  <<: *defaults
  database: contact_production
