# script to combing all the client_data subclasses into one table using singke table inheritence 
#
# These classes can probalby be removed altogether 
#    bizzspot, brownbook, byzlysts, citydata, citysearch*, craigslist (no data table) 
#    crunchbase*, cylex, jayde, judys_book

insert into client_data(business_id, email, secrets, status, force_update, listing_url, created_at, updated_at, category_id, do_not_sync, type) select business_id, email, secrets, status, force_update, listing_url, created_at, updated_at, angies_list_category_id, do_not_sync, "AngiesList" from angies_lists;
insert into client_data(business_id, force_update, secrets, username, created_at, updated_at, do_not_sync, type) select business_id, force_update, secrets, username, created_at, updated_at, do_not_sync, "Aol" from aols;
insert into client_data(business_id, local_url, email, secrets, status, force_update, created_at, updated_at, category_id, do_not_sync, type) select business_id, local_url, email, secrets, status, force_update, created_at, updated_at, bing_category_id, do_not_sync, "Bing" from bings; 
insert into client_data(business_id, created_at, updated_at, secrets, do_not_sync, force_update, email, username, type ) select business_id, created_at, updated_at, secrets, do_not_sync, force_update, email, username, "Bizzspot" from bizzspots;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, email, type) select business_id, created_at, updated_at, secrets, force_update, email, "Brownbook" from brownbooks; 
insert into client_data(business_id, created_at, updated_at, secrets, force_update, email, type) select business_id, created_at, updated_at, secrets, force_update, email, "Businesscom" from businesscoms; 
insert into client_data(business_id, created_at, updated_at, secrets, force_update, email, category_id, type) select business_id, created_at, updated_at, secrets, force_update, email, businessdb_category_id, "Businessdb" from businessdbs; 
insert into client_data(business_id, created_at, updated_at, secrets, force_update, email, do_not_sync, category_id, type) select business_id, created_at, updated_at, secrets, force_update, email, do_not_sync, citisquare_category_id, "Citisquare" from citisquares;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, email, do_not_sync, category_id, type) select business_id, created_at, updated_at, secrets, force_update, email, do_not_sync, citydata_category_id, "Citydata" from citydata;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, username, do_not_sync, category_id, type) select business_id, created_at, updated_at, secrets, force_update, username, do_not_sync, cornerstonesworld_category_id, "Cornerstonesworld" from cornerstonesworlds;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, email, facebook_signin, listing_url, type) select business_id, created_at, updated_at, secrets, force_update, email, facebook_signin, listing_url, "Citysearch" from citysearches;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, email, do_not_sync, category_id, type) select business_id, created_at, updated_at, secrets, force_update, email, do_not_sync, digabusiness_category_id, "Digabusiness" from digabusinesses; 
insert into client_data(business_id, created_at, updated_at, secrets, force_update, email, do_not_sync, type) select business_id, created_at, updated_at, secrets, force_update, email, do_not_sync, "Discoverourtown" from discoverourtowns; 
insert into client_data(business_id, created_at, updated_at, secrets, force_update, username, do_not_sync, category_id, type) select business_id, created_at, updated_at, secrets, force_update, username, do_not_sync, ebusinesspage_category_id, "Ebusinesspage" from ebusinesspages;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, category_id, type) select business_id, created_at, updated_at, secrets, force_update, expertfocus_category_id, "Expertfocus" from expertfocus;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, do_not_sync, username, type) select business_id, created_at, updated_at, secrets, force_update, do_not_sync, username,  "Expressbusinessdirectories" from  expressbusinessdirectories;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, email, category_id, type) select business_id, created_at, updated_at, secrets, force_update, email, expressupdateusa_category_id, "Expressupdateusa" from expressupdateusas;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, do_not_sync, email, category_id, type) select business_id, created_at, updated_at, secrets, force_update, do_not_sync, email, ezlocal_category_id, "Ezlocal" from ezlocals;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, do_not_sync, status, email, category_id, profile_category_id, type) select business_id, created_at, updated_at, secrets, force_update, do_not_sync, status, email, facebook_category_id, facebook_profile_category_id, "Facebook" from facebooks;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, do_not_sync, status, email, facebook_signin, foursquare_page, category_id, type) select business_id, created_at, updated_at, secrets, force_update, do_not_sync, status, email, facebook_signin, foursquare_page, foursquare_category_id, "Foursquare" from foursquares;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, do_not_sync, username, type) select business_id, created_at, updated_at, secrets, force_update, do_not_sync, username, "Freebusinessdirectory" from freebusinessdirectories;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, do_not_sync, email, type) select business_id, created_at, updated_at, secrets, force_update, do_not_sync, email, "Getfave" from getfaves;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, do_not_sync, username, category_id, type) select business_id, created_at, updated_at, secrets, force_update, do_not_sync, username, gomylocal_category_id, "Gomylocal" from gomylocals;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, do_not_sync, email, youtube_channel, places_url, cookies, category_id, type) select business_id, created_at, updated_at, secrets, force_update, do_not_sync, email, youtube_channel, places_url, cookies, google_category_id, "Google" from googles;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, do_not_sync, status, listing_url, email, type) select business_id, created_at, updated_at, secrets, force_update, do_not_sync, status, listing_url, email, "Hotfrog" from hotfrogs; 
insert into client_data(business_id, created_at, updated_at, secrets, force_update, do_not_sync, username, category_id, type) select business_id, created_at, updated_at, secrets, force_update, do_not_sync, username, hyplo_category_id, "Hyplo" from hyplos;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, do_not_sync, email, category_id, type) select business_id, created_at, updated_at, secrets, force_update, do_not_sync, email, ibegin_category_id, "Ibegin" from ibegins;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, do_not_sync, email, listing_url, facebook_signin, status, category_id, type) select business_id, created_at, updated_at, secrets, force_update, do_not_sync, email, listing_url, facebook_signin, status,insider_page_category_id, "InsiderPage" from insider_pages;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, type) select business_id, created_at, updated_at, secrets, force_update, "Jayde" from jaydes;
insert into client_data(business_id, created_at, updated_at, secrets, force_update, email, listing_url, facebook_signin, status, type) select business_id, created_at, updated_at, secrets, force_update, email, listing_url, facebook_signin, status, "JudysBook" from judys_books;

