browser = Watir::Browser.start("http://ezlocal.com/")
browser.a(:text => "List Your Business").click
browser.text_field(:id =>"tPhone1").set business['phone_area_code']
browser.text_field(:id => "tPhone2").set business['phone_prefix']
browser.text_field(:id => "tPhone3").set business['phone_number']
browser.a(:id => "bSubmit").click
browser.text_field(:id => "tBusinessName").set business['name']
browser.text_field(:id => "tPhone1").set business['phone_area_code']
browser.text_field(:id => "tPhone2").set business['phone_prefix']
browser.text_field(:id => "tPhone3").set business['phone_number']
browser.text_field(:id => "tBusinessAddress").set business['address']
browser.text_field(:id => "tBusinessAddress2").set business['address2']
browser.text_field(:id => "tFax1").set business['fax_area_code']
browser.text_field(:id => "tFax2").set business['fax_prefix']
browser.text_field(:id => "tFax3").set business['fax_number']
browser.text_field(:id =>"tBusinessCity").set business['city']
browser.select_list(:id => "dBusinessState").select business['state_long']
browser.text_field(:id => "tBusinessZip").set business['zip']
browser.text_field(:id => "tFirstName").set business['first_name']
browser.text_field(:id => "tLastName").set business['last_name']
browser.text_field(:id => "tContactPhone1").set business['phone_area_code']
browser.text_field(:id => "tContactPhone2").set business['phone_prefix']
browser.text_field(:id, "tContactPhone3").set business['phone_number']
browser.text_field(:id => "tEmail").set business['email']
browser.a(:id => "bSubmit").click
browser.a(:text => "None of these, just a free basic listing.").click
browser.text_field(:id => "tDescription").set business['description']
browser.select_list(:id => "dCategory1").select business['ezlocal_category1']
browser.select_list(:id => "dCategory2").select business['ezlocal_category2']
browser.select_list(:id => "dCategory3").select business['ezlocal_category3']
browser.text_field(:id => "tWebsite").set business['website']
# browser.file_field(:id => "fuImage").set "C:\\Users\\jonathan\\Downloads\\me.jpg"
browser.text_field(:id => "btnContinue").click
browser.text_field(:id => "chkTerms").click
browser.text_field(:id => "bFinish").click
browser.a(:text => "finish and submit your profile.").click
