data = {}
data['business_name']      = 'Shogun Plumbing'
data['contact_first_name'] = 'Bill'
data['contact_last_name']  = 'Snorgie'
data['email']              = 'abcx4@blazingdev.com'
data['gender']             = 'Male'
data['address']            = '2934 Leeway Dr'
data['address2']           = ''
data['birth_month']        = 'Nov'
data['phone']              = '573-529-2374'
data['birth_day']          = '9'
data['zip']                = '65202'
data['city']               = 'Columbia'
data['state']              = 'MO'
data['birth_year']         = '1980'
data['password']           = '1zqa2xwsK'
data['website']            = 'http://blazingsuana.com'
data['yelp_category']      = ['Pets', 'Pet Stores']

browser = Watir::Browser.start("http://ezlocal.com/")
browser.a(:text => "List Your Business").click
browser.text_field(:id =>"tPhone1").set data['phone_area_code']
browser.text_field(:id => "tPhone2").set data['phone_prefix']
browser.text_field(:id => "tPhone3").set data['phone_number']
browser.a(:id => "bSubmit").click
browser.text_field(:id => "tBusinessName").set data['name']
browser.text_field(:id => "tPhone1").set data['phone_area_code']
browser.text_field(:id => "tPhone2").set data['phone_prefix']
browser.text_field(:id => "tPhone3").set data['phone_number']
browser.text_field(:id => "tBusinessAddress").set data['address']
browser.text_field(:id => "tBusinessAddress2").set data['address2']
browser.text_field(:id => "tFax1").set data['fax_area_code']
browser.text_field(:id => "tFax2").set data['fax_prefix']
browser.text_field(:id => "tFax3").set data['fax_number']
browser.text_field(:id =>"tBusinessCity").set data['city']
browser.select_list(:id => "dBusinessState").select data['state_long']
browser.text_field(:id => "tBusinessZip").set data['zip']
browser.text_field(:id => "tFirstName").set data['first_name']
browser.text_field(:id => "tLastName").set data['last_name']
browser.text_field(:id => "tContactPhone1").set data['phone_area_code']
browser.text_field(:id => "tContactPhone2").set data['phone_prefix']
browser.text_field(:id, "tContactPhone3").set data['phone_number']
browser.text_field(:id => "tEmail").set data['email']
browser.a(:id => "bSubmit").click
browser.a(:text => "None of these, just a free basic listing.").click
browser.text_field(:id => "tDescription").set data['description']
browser.select_list(:id => "dCategory1").select data['ezlocal_category1']
browser.select_list(:id => "dCategory2").select data['ezlocal_category2']
browser.select_list(:id => "dCategory3").select data['ezlocal_category3']
browser.text_field(:id => "tWebsite").set data['website']
# browser.file_field(:id => "fuImage").set "C:\\Users\\jonathan\\Downloads\\me.jpg"
browser.text_field(:id => "btnContinue").click
browser.text_field(:id => "chkTerms").click
browser.text_field(:id => "bFinish").click
browser.a(:text => "finish and submit your profile.").click
