data = {}
data[ 'email' ]			= business.yellowees.first.username
data[ 'password' ]		= business.yellowees.first.password#6UfOlU2YGmQ
data[ 'business' ]		= business.business_name
data[ 'query' ]			= business.city + ", " + business.state + ", United States"
data[ 'address' ]		= business.address
data[ 'address2' ]		= business.address2
data[ 'zip' ]			= business.zip
data[ 'phone' ]			= business.local_phone
data[ 'website' ]		= business.company_website
data['cat11']			= "Auto Service"
data['cat12']			= "Auto Glass"
data['cat13']			= ""
data['cat21']			= "Beauty and Spas"
data['cat22']			= "Barbers"
data['cat23']			= ""
data['cat31']			= "Computers"
data['cat32']			= ""
data['cat33']			= ""
data[ 'hours' ]			= Justclicklocal.get_hours( business )
data[ 'description' ]		= business.business_description
data[ 'founded' ]		= business.year_founded
data
