data = {}
data[ 'phone' ] = business.local_phone
data[ 'email' ] = business.magicyellows.first.email
data[ 'business' ] = business.business_name
data[ 'address' ] = business.address
data[ 'city' ] = business.city
data[ 'state' ] = business.state_name
data[ 'zip' ] = business.zip
data[ 'first_name' ] = business.contact_first_name
data[ 'last_name' ] = business.contact_last_name
data[ 'claim_business'] = 'yes'
data[ 'fullname' ] = data[ 'first_name' ] + " " + data[ 'last_name' ]
data[ 'business_category']  = business.category1
data[ 'business_description']  = business.business_description	
data[ 'payment_option'] = Magicyellow.payment_methods(business)
data[ 'relation_to_business' ] = 'Agent'
data[ 'is_owner'] = 'Yes'
data[ 'additional_services' ] = ' '
data[ 'additional_products' ] = ' '
data[ 'additional_brands' ] = ' '
data